### ISSUE TITLE
Error trying to add as Air Quality sensor (homekit)

### ISSUE THREAD

**Issue by johnsturgeon** [FlyingDiver/Indigo-miniPurple#2]
I was wondering if something needs to be done by this plugin to support being used by HomeKit as an Air Quality sensor.

I tried adding it and I got this error:
```
   HomeKit Bridge Error            Exception in homekit.setAttributeValue line 1560: global name 'dev' is not defined
							 CODE: self.logger.error (u"Cannot set {} value of {} because it is not an attribute".format(attribute, dev.Alias.value))

   HomeKit Bridge Error            Exception in homekit.detCharacteristicValues line 1070: 'service_AirQualitySensor' object has no attribute 'AirQuality'
							 CODE: if characteristic not in self.characterDict: self.characterDict[characteristic] = getattr (self, characteristic).value

For object id 855142381 alias 'Purple Air (indoor)'
```

I would understand if you don't know, and I should follow up with the HomeKit plugin...  I'm just curious

**Comment by FlyingDiver** [comment]
I have no idea what HomeKit needs to use an Air Quality sensor.  Maybe it's looking for a state called 'AirQuality'?

**Comment by johnsturgeon** [comment]
I'll do a bit of research and see how to make sure that a device is 'homekit' compatible in Indigo.

**Comment by FlyingDiver** [comment]
Not just HomeKit, but specifically what the HomeKit Bridge is looking for.

**Comment by johnsturgeon** [comment]
Issue filed here:
https://github.com/Colorado4Wheeler/HomeKit-Bridge/issues/139
